### ISSUE TITLE
Marking glossary terms as untranslateable

### ISSUE THREAD

**Issue by zonuM-alyak** [desmosinc/pontoon#6]
**Is your feature request related to a problem? Please describe.**

Right now we house our glossary in a Google Sheet, the problem with this is as our glossary grows it becomes more and more likely a linguist will miss a word. 

**Describe the solution you'd like**

It would be great if Pontoon could parse the strings and recognize when a term is marked as untranslateable in our glossary, subsequently letting the linguist know that term should stay in English. 

For reference: Lokalise TMS seems to do this really well.

**Comment by anandthakker** [comment]
The new "Terms" feature takes care of this
