### ISSUE TITLE
Auto-suggesting glossary terms

### ISSUE THREAD

**Issue by zonuM-alyak** [desmosinc/pontoon#7]
**Is your feature request related to a problem? Please describe.**

We have quite a few glossary terms and are adding more as time goes on. While translators can try it is often hard to keep an eye on all glossary terms as they are working. 

**Describe the solution you'd like**

It would be great if Pontoon could recognize our glossary terms and suggest the correct translation to the linguist while they are working.

**Describe alternatives you've considered**

If it can't suggest the correct term it would be great if it could at least flag the word letting the translator know that they should consult the glossary.

**Comment by anandthakker** [comment]
Done thanks to Pontoon's Terms feature
